# Generated by Django 4.2.5 on 2023-09-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooster_import", "0002_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
