# Generated by Django 4.2.5 on 2023-09-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooster_import", "0003_calendar_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="url",
            field=models.URLField(max_length=255),
        ),
    ]
