# Generated by Django 4.2.5 on 2023-09-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooster_import', '0004_alter_calendar_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='CalendarSource',
        ),
    ]
