# Generated by Django 4.2.5 on 2023-09-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooster_import", "0009_remove_event_group_event_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendar",
            name="tracks",
        ),
        migrations.AddField(
            model_name="calendar",
            name="groups",
            field=models.ManyToManyField(to="rooster_import.group"),
        ),
    ]
