# Generated by Django 4.2.5 on 2024-01-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooster_import", "0010_remove_calendar_tracks_calendar_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="lecturers",
            field=models.ManyToManyField(to="rooster_import.lecturer"),
        ),
    ]
