# Generated by Django 4.2.5 on 2024-01-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rooster_import", "0011_lecturer_event_lecturers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendar",
            name="courses",
        ),
        migrations.CreateModel(
            name="CourseLecturerSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooster_import.calendar",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooster_import.course",
                    ),
                ),
                ("lecturers", models.ManyToManyField(to="rooster_import.lecturer")),
            ],
        ),
    ]
